version: '2'
services:
  app:
    build: .
    volumes:
      - .:/app
      - ./public/system/:/app/public/system/
    ports:
      - 3000:80
  nginx:
    volumes:
      - /Users/antodoms/rmit-projects/beaconoid/nginx.devel.conf
    ports:
      - 80:80
  # db_backup:
  #   command: /bin/true