version: '2'
services:
  db:
    image: postgres
    ports:
    - "5432"
  redis:
    image: redis:3.0.5
    ports:
      - '6379'
    volumes:
      - /var/lib/redis/data
  mongo:
    image: mongo:3.4.4
    ports:
      - '27017:27017'
  app:
    command: bundle exec puma -C config/puma.rb
    depends_on:
      - db
      - redis
      - mongo
  nginx:
    image: nginx
    volumes_from:
      - app
    depends_on:
      - app

  # db_backup:
  #   image: equinoxone/postgres_backup:0.1
  #   depends_on:
  #     - db
  #   volumes:
  #     - ./backup:/backup
  #   environment:
  # #    - PGUSER=postgres
  # #    - PGPASSWORD=
  # #    - PGPORT=5432
  # #    - PGHOST=db
  #     - PGDATABASE=beacon_web_console_development