development:
  adapter: redis
  url: redis://127.0.0.1:6379/1
  namespace: beaconoid

staging:
  adapter: redis
  url: redis://redis:6379/1
  namespace: beaconoid

test:
  adapter: async

production:
  adapter: redis
  url: redis://localhost:6379/1
  namespace: beaconoid
