development:
  clients:
    default:
      database: beacon_web_console_development_mongo
      hosts:
        - 127.0.0.1:27017
test:
  clients:
    default:
      database: beacon_web_console_test_mongo
      hosts:
        - 127.0.0.1:27017
      options:
        read:
          mode: :primary
        max_pool_size: 1
production:
  clients:
    default:
      database: beacon_web_console_production_mongo
      hosts:
        - 127.0.0.1:27017